A00082654_Rory_Sheridan_A1

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('products.csv')
df

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Product_Weight_g,Moisture_pct,Temperature_C,Processing_Time_min,Quality_Grade,Defect
0,B001,2026-09-17,B,Enhanced,Day,482.9,11.18,21.0,33.5,B,Yes
1,B002,2026-09-07,C,Standard,Day,496.3,11.17,22.1,33.6,A,No
2,B003,2026-09-14,B,Standard,Night,492.3,11.65,20.5,35.8,A,No
3,B004,2026-09-16,C,Standard,Day,513.1,11.55,20.5,37.6,B,No
4,B005,2026-09-10,A,Enhanced,Day,494.5,12.57,21.6,45.7,B,Yes
...,...,...,...,...,...,...,...,...,...,...,...
115,B116,2026-09-28,A,Enhanced,Night,502.8,12.09,21.6,43.0,A,No
116,B117,2026-09-26,C,Standard,Day,506.7,12.07,22.3,29.4,B,No
117,B118,2026-09-22,C,Enhanced,Night,516.9,11.61,22.2,50.2,C,No
118,B048,2026-09-18,A,Standard,Day,488.5,12.18,23.0,37.7,B,No
119,B120,2026-09-18,B,Standard,Night,510.9,12.09,21.1,41.9,B,No

In [8]:
df.describe()

       Product_Weight_g  Moisture_pct  Temperature_C  Processing_Time_min
count        120.000000    118.000000     120.000000           119.000000
mean         501.530833     11.660339      23.077500            41.831933
std           11.582621      0.701214      17.243888             8.606560
min          476.200000      9.610000      18.200000            26.400000
25%          494.775000     11.190000      20.800000            37.750000
50%          501.800000     11.660000      21.500000            41.700000
75%          508.700000     12.097500      22.200000            44.950000
max          568.000000     13.510000     210.000000           112.000000

In [9]:
df.describe(exclude='number')

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Quality_Grade,Defect
count,120,120,120,120,120,119,120
unique,119,27,3,2,2,3,2
top,B048,2026-09-17,A,Standard,Day,B,No
freq,2,9,45,65,79,77,107

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Batch_ID             120 non-null    str
 1   Production_Date      120 non-null    str
 2   Factory              120 non-null    str
 3   Process_Type         120 non-null    str
 4   Shift                120 non-null    str
 5   Product_Weight_g     120 non-null    float64
 6   Moisture_pct         118 non-null    float64
 7   Temperature_C        120 non-null    float64
 8   Processing_Time_min  119 non-null    float64
 9   Quality_Grade        119 non-null    str
 10  Defect               120 non-null    str
dtypes: float64(4), str(7)
memory usage: 10.4 KB

In [7]:
df.shape

(120, 11)

In [13]:
df.duplicated().sum()

np.int64(1)

In [14]:
df[df.duplicated()]

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Product_Weight_g,Moisture_pct,Temperature_C,Processing_Time_min,Quality_Grade,Defect
118,B048,2026-09-18,A,Standard,Day,488.5,12.18,23.0,37.7,B,No

In [15]:
df.isna().sum()

Batch_ID               0
Production_Date        0
Factory                0
Process_Type           0
Shift                  0
Product_Weight_g       0
Moisture_pct           2
Temperature_C          0
Processing_Time_min    1
Quality_Grade          1
Defect                 0
dtype: int64